services:
  django_app:
    build:
      context: ./django_app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=django_app.settings
    command: ["gunicorn", "django_app.wsgi", "--bind", "0.0.0.0:8000"]

  fastapi_app:
    build:
      context: ./fastapi_app
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]

  robyn_app:
    build:
      context: ./robyn_app
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    command: ["python", "app.py"]

  wrk_benchmark:
    image: python:3.11-slim
    volumes:
      - .:/app
    working_dir: /app
    command: ["python", "benchmark_runner.py"]
